import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/sidebar/app-sidebar";
import { SessionProvider } from "next-auth/react"
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <SidebarProvider>
            <AppSidebar />
            <SidebarTrigger />
            <main className="all-none w-full h-screen p-0 m-0">
              {children}
            </main>
            <Toaster position="top-right" richColors />
          </SidebarProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
